<a href="https://colab.research.google.com/github/Korukonda-praveen/Data-Analytics/blob/master/DA_pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [69]:
print('hi boss gud mrng')

hi boss gud mrng

In [70]:
!pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.13/dist-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas) (2026.4)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [71]:
# with list
import pandas as pd
data=[1,2,3,4,5]
s=pd.Series(data)
print(s)

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [72]:
s=pd.Series(data=[1,2,3,4,5],index=['a','b','c','d','e'])
print(s)

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [73]:
# with dict
s2=pd.Series({'a':10,'b':20,'c':30})
print(s2)

a    10
b    20
c    30
dtype: int64

In [74]:
#Accessing elements of Series
import pandas as pd
data=['g','p','e','k','a','f','o','r','g','e','e','k','s']
ser=pd.Series(data)
print(ser[0:4])
print(ser[2:5])
print(ser[-3:])
print(ser[7:9])

0    g
1    p
2    e
3    k
dtype: object
2    e
3    k
4    a
dtype: object
10    e
11    k
12    s
dtype: object
7    r
8    g
dtype: object

In [75]:
# updating elements of Series
ser['e']='z'
print(ser)

0     g
1     p
2     e
3     k
4     a
5     f
6     o
7     r
8     g
9     e
10    e
11    k
12    s
e     z
dtype: object

In [76]:
# update using indexing
s1=pd.Series([10,20,30,40],index=['a','b','c','d'])
print(s1)
# update an element
s1['a']=50
print(s1)

a    10
b    20
c    30
d    40
dtype: int64
a    50
b    20
c    30
d    40
dtype: int64

In [77]:
# update the indexing value
s1=pd.Series([10,20,30,40],index=['a','b','c','d'])
print(s1)
# update an index and elemet
s1['e']=90
print(s1)

a    10
b    20
c    30
d    40
dtype: int64
a    10
b    20
c    30
d    40
e    90
dtype: int64

In [78]:
# drop a index and element using drop
# delete as element
s1=s1.drop('b')
print(s1)

a    10
c    30
d    40
e    90
dtype: int64

In [79]:
# student marks question
marks=pd.Series([78,85,92,67,88],index=[101,102,103,104,105])
print(marks)
print(marks[103])
marks[104]=75
print(marks)
marks=marks.drop(102)
print(marks)
marks[106]=90
print(marks)

101    78
102    85
103    92
104    67
105    88
dtype: int64
92
101    78
102    85
103    92
104    75
105    88
dtype: int64
101    78
103    92
104    75
105    88
dtype: int64
101    78
103    92
104    75
105    88
106    90
dtype: int64

In [80]:
# employee slaries
salary=pd.Series([35000,42000,30000,50000,45000],index=[1001,1002,1003,1004,1005])
print('--- Before update---')
print(salary)
salary[1003]=40000
print("--- After Update ---")
print(salary)
salary=salary.drop(1002)
print("\n--- After Drop ---")
print(salary)
salary[1006]=55000
print("\n--- After Addition ---")
print(salary)
print("\n--- First 3 Employees ---")
print(salary[:3])

--- Before update---
1001    35000
1002    42000
1003    30000
1004    50000
1005    45000
dtype: int64
--- After Update ---
1001    35000
1002    42000
1003    40000
1004    50000
1005    45000
dtype: int64

--- After Drop ---
1001    35000
1003    40000
1004    50000
1005    45000
dtype: int64

--- After Addition ---
1001    35000
1003    40000
1004    50000
1005    45000
1006    55000
dtype: int64

--- First 3 Employees ---
1001    35000
1003    40000
1004    50000
dtype: int64

In [81]:
# Product prices
Prices=pd.Series([500,750,1200,900,1500],
index=['P101','P102','P103','P104','P105'])
print("--Before and changes---")
print(Prices)
print('\n--- Display on the element with index P103 ---')
print(Prices['P103'])

print('\n--- change the elemet 750 to 800 ---')
Prices['P102']=800
print(Prices)


print('\n--- After Drop ---')
Prices=Prices.drop('P104')
print(Prices)
print("\n--- After Addition ---")
Prices['P106']=2000
print(Prices)

--Before and changes---
P101     500
P102     750
P103    1200
P104     900
P105    1500
dtype: int64

--- Display on the element with index P103 ---
1200

--- change the elemet 750 to 800 ---
P101     500
P102     800
P103    1200
P104     900
P105    1500
dtype: int64

--- After Drop ---
P101     500
P102     800
P103    1200
P105    1500
dtype: int64

--- After Addition ---
P101     500
P102     800
P103    1200
P105    1500
P106    2000
dtype: int64

In [82]:
# daily temperature
temp= pd.Series([31,32,34,33,35,36,34],
index=['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'])
print('--- Before any changes ---')
print(temp)

print('\n--- Display the temperature from Monday to Wednesday ---')
print(temp[:3])

print("\n--- Change Thursday's temperature to 32 ---")
temp['Thursday']=32
print(temp)

print("\n--- Delete Saturday's temperature ---")
temp=temp.drop('Saturday')
print(temp)

print('\n--- Add Monday of yhe next week wih temperature ---')

temp['next_Monday']=30
print(temp)

--- Before any changes ---
Monday       31
Tuesday      32
Wednesday    34
Thursday     33
Friday       35
Saturday     36
Sunday       34
dtype: int64

--- Display the temperature from Monday to Wednesday ---
Monday       31
Tuesday      32
Wednesday    34
dtype: int64

--- Change Thursday's temperature to 32 ---
Monday       31
Tuesday      32
Wednesday    34
Thursday     32
Friday       35
Saturday     36
Sunday       34
dtype: int64

--- Delete Saturday's temperature ---
Monday       31
Tuesday      32
Wednesday    34
Thursday     32
Friday       35
Sunday       34
dtype: int64

--- Add Monday of yhe next week wih temperature ---
Monday         31
Tuesday        32
Wednesday      34
Thursday       32
Friday         35
Sunday         34
next_Monday    30
dtype: int64

In [83]:
# Bank Account Balances
Balances=pd.Series([25000,45000,32000,10000,60000],
index=['A101','A102','A103','A104','A105'])
print('--- Before any changes ---')
print(Balances)

print('\n--- Display the account balance of A103 ---')
print(Balances['A103'])

print('\n--- Update A104 balance to 25000 ---')
Balances['A104']=25000
print(Balances)

print('\n--- Delete Account A101 ---')
Balances=Balances.drop('A101')
print(Balances)

print('\n--- Add Account A106 with balance 40000 ---')
Balances['A106']=40000
print(Balances)

--- Before any changes ---
A101    25000
A102    45000
A103    32000
A104    10000
A105    60000
dtype: int64

--- Display the account balance of A103 ---
32000

--- Update A104 balance to 25000 ---
A101    25000
A102    45000
A103    32000
A104    25000
A105    60000
dtype: int64

--- Delete Account A101 ---
A102    45000
A103    32000
A104    25000
A105    60000
dtype: int64

--- Add Account A106 with balance 40000 ---
A102    45000
A103    32000
A104    25000
A105    60000
A106    40000
dtype: int64

What is Dataframe:
a Dataframe is a two-dimensional labeled data structure in pandas
DataFrame contains rows and columns

 we can create dataframe using "pd.DataFrame()"

In [84]:
# dataframe creation
# using list
data=[
    ["ravi",22,30000],
    ["priya",24,40000],
    ["Arun",21,28000]
    ]

df=pd.DataFrame(data,columns=['Name','Age','Salary'])
print(df)

    Name  Age  Salary
0   ravi   22   30000
1  priya   24   40000
2   Arun   21   28000

In [85]:
# using tuple creating a dataframe
data=(
    ("jaya",22,30000),
    ("tony",24,40000),
    ("dhoom",21,28000)
)

df=pd.DataFrame(data,columns=['Name','Age','Salary'])
print(df)

    Name  Age  Salary
0   jaya   22   30000
1   tony   24   40000
2  dhoom   21   28000

In [86]:
# using dict creating a dataframe
data={
    'Name':['ravi','priya','Arun'],
    'Age':[22,24,21],
    'Salary':[30000,40000,28000]
}

df=pd.DataFrame(data)
print(df)

    Name  Age  Salary
0   ravi   22   30000
1  priya   24   40000
2   Arun   21   28000

In [87]:
# create a dataframe sales and profit every month first 6 months of the year
sales=[
      ['jan',100,2000],
      ['feb',200,3000],
      ['mar',300,4000],
      ['apr',400,5000],
      ['may',500,6000],
      ['jun',600,7000]
]
df=pd.DataFrame(sales,columns=['Month','Sales','Profit'])
print(df)

  Month  Sales  Profit
0   jan    100    2000
1   feb    200    3000
2   mar    300    4000
3   apr    400    5000
4   may    500    6000
5   jun    600    7000

In [88]:
# create a dataframe using set
my_set={100,200,300,400}

df=pd.DataFrame(list(my_set),columns=['values'])
print(df)

   values
0     200
1     100
2     400
3     300

In [89]:
# creating single series into dataframe
s=pd.Series([1,2,3,4],name='Numbers')
df=s.to_frame()
print(df)

   Numbers
0        1
1        2
2        3
3        4

In [90]:
# creating two series into dataframe
s2 = pd.Series([9,5,7,8])
s3 = pd.Series([1,2,3,4])
d = {
    "marks-A" :s,
    "marks-B" :s2,
    "marks-c" :s3
 }
df = pd.DataFrame(d)
print(df)

   marks-A  marks-B  marks-c
0        1        9        1
1        2        5        2
2        3        7        3
3        4        8        4

In [91]:
# rename the column
s2 = pd.Series([9,5,7,8,7,8,9,6,7,7,8,9])
s3 = pd.Series([1,2,3,4,7,6,5,5,4,5,6,7])
d = {
    "marks-A" :s,
    "marks-B" :s2,
    "marks-c" :s3
 }
df = pd.DataFrame(d)
df.columns=['py','da','mysql'] #renaming the columns
print(df)

     py  da  mysql
0   1.0   9      1
1   2.0   5      2
2   3.0   7      3
3   4.0   8      4
4   NaN   7      7
5   NaN   8      6
6   NaN   9      5
7   NaN   6      5
8   NaN   7      4
9   NaN   7      5
10  NaN   8      6
11  NaN   9      7

In [92]:
# renaming the exising columns (inplace=true using for permanent change)
s=pd.DataFrame([[1,2],[3,4]])
s.columns=['A','B']
print(s)
print("-"*45)
s.rename(columns={'A':'Tony','B':'Stark'},inplace=True)
print(s)

   A  B
0  1  2
1  3  4
---------------------------------------------
   Tony  Stark
0     1      2
1     3      4

In [93]:
# viewing and top and bottom using head and tail
s2 = pd.Series([9,5,7,8,7,8,9,6,7,7,8,9])
s3 = pd.Series([1,2,3,4,7,6,5,5,4,5,6,7])
print(s2.head(5))
print(s3.tail(5))

0    9
1    5
2    7
3    8
4    7
dtype: int64
7     5
8     4
9     5
10    6
11    7
dtype: int64

In [94]:
# check the length of the series
print('length:',len(s2))

length: 12

In [95]:
# checking the shape
s=pd.DataFrame([[1,2],[3,4]])
print('shape:',s.shape)

shape: (2, 2)

In [96]:
# checking the values
print('values:',s3.values)

values: [1 2 3 4 7 6 5 5 4 5 6 7]

In [97]:
# checking the index
print('index:',s3.index)

index: RangeIndex(start=0, stop=12, step=1)

In [98]:
# question 1
employees=[
    ["ravi",22,"vizag",30000],
    ["priya",24,"hyd",40000],
    ["Arun",21,"delhi",28000],
    ["praveen",20,"Goa",30000],
    ["Tony",42,"usa",70000]
]
df=pd.DataFrame(employees,columns=['Name','Age','City','Salary'])
print(df)

      Name  Age   City  Salary
0     ravi   22  vizag   30000
1    priya   24    hyd   40000
2     Arun   21  delhi   28000
3  praveen   20    Goa   30000
4     Tony   42    usa   70000

In [99]:
# question 2
data={
    "product":['shirt','moblie','chips','watch','shoes'],
    "category":['fashion','electronics','food','electronics','footwear'],
    "price":[2000,25000,50,2500,3000],
    "quantity":[1,2,3,1,2]

}
df=pd.DataFrame(data)
print(df)

  product     category  price  quantity
0   shirt      fashion   2000         1
1  moblie  electronics  25000         2
2   chips         food     50         3
3   watch  electronics   2500         1
4   shoes     footwear   3000         2

In [100]:
# question 3
data = [
    {"Student_ID": 101, "Name": "Praveen", "Course": "AI", "Marks": 95},
    {"Student_ID": 102, "Name": "Tony", "Course": "Python", "Marks": 99},
    {"Student_ID": 103, "Name": "Rocky", "Course": "Sql", "Marks": 85},
    {"Student_ID": 104, "Name": "Victor", "Course": "DA", "Marks": 92},
    {"Student_ID": 105, "Name": "Thor", "Course": "ML", "Marks": 88}
]

df=pd.DataFrame(data)
print(df)

   Student_ID     Name  Course  Marks
0         101  Praveen      AI     95
1         102     Tony  Python     99
2         103    Rocky     Sql     85
3         104   Victor      DA     92
4         105     Thor      ML     88

In [101]:
# question 4
data=(
    (101,'praveen','IT',2),
    (102,'Tony','IT',8),
    (103,'Rocky','HR',6),
    (104,'Victor','Sales',5),
    (105,'Thor','finance',6)
)
df=pd.DataFrame(data,columns=['Employee_ID','Name','Department','Experience'])
print(df)

   Employee_ID     Name Department  Experience
0          101  praveen         IT           2
1          102     Tony         IT           8
2          103    Rocky         HR           6
3          104   Victor      Sales           5
4          105     Thor    finance           6

In [102]:
# question 5
Name=pd.Series(['ravi','praveen','tony','rocky','thor'])
Age=pd.Series([20,21,42,32,1500])
city=pd.Series(['Mumbai','Vizag','Malibu','kgf','Asgard'])

df=pd.DataFrame({'name':Name,'age':Age,'city':city})
print(df)

      name   age    city
0     ravi    20  Mumbai
1  praveen    21   Vizag
2     tony    42  Malibu
3    rocky    32     kgf
4     thor  1500  Asgard

In [103]:
# Selecting and flitering
data={
      'name':['Ravi','priya','Arun','Sneha','Kiran','Anjail','Vikram','Meena'],
      'age':[22,24,21,25,23,26,20,27],
      'city':['Hyderbad','Chennai','Bangalore',
              'Hyderbad','Mumbai','Chennai','Bangalore','Mumbai'],
      'salary':[30000,40000,28000,50000,35000,45000,25000,55000]}

df=pd.DataFrame(data,index=[101,102,103,104,105,106,107,108])
print(df)

       name  age       city  salary
101    Ravi   22   Hyderbad   30000
102   priya   24    Chennai   40000
103    Arun   21  Bangalore   28000
104   Sneha   25   Hyderbad   50000
105   Kiran   23     Mumbai   35000
106  Anjail   26    Chennai   45000
107  Vikram   20  Bangalore   25000
108   Meena   27     Mumbai   55000

In [104]:
# for the top the values
print(df.head())

      name  age       city  salary
101   Ravi   22   Hyderbad   30000
102  priya   24    Chennai   40000
103   Arun   21  Bangalore   28000
104  Sneha   25   Hyderbad   50000
105  Kiran   23     Mumbai   35000

In [105]:
# for the bottom the values
print(df.tail())

       name  age       city  salary
104   Sneha   25   Hyderbad   50000
105   Kiran   23     Mumbai   35000
106  Anjail   26    Chennai   45000
107  Vikram   20  Bangalore   25000
108   Meena   27     Mumbai   55000

In [106]:
# for the info the the dataframe
print(df.info())

<class 'pandas.core.frame.DataFrame'>
Index: 8 entries, 101 to 108
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    8 non-null      object
 1   age     8 non-null      int64
 2   city    8 non-null      object
 3   salary  8 non-null      int64
dtypes: int64(2), object(2)
memory usage: 320.0+ bytes
None

In [107]:
# for the what type values are present in the dataframe
print(df.describe())

            age        salary
count   8.00000      8.000000
mean   23.50000  38500.000000
std     2.44949  10862.780491
min    20.00000  25000.000000
25%    21.75000  29500.000000
50%    23.50000  37500.000000
75%    25.25000  46250.000000
max    27.00000  55000.000000

In [108]:
# for lenght of the dataframe
print(len(df))

8

In [109]:
# for the rows and colomns
print(df.shape)

(8, 4)

In [110]:
# for the index range
print(df.index)

Index([101, 102, 103, 104, 105, 106, 107, 108], dtype='int64')

In [111]:
# selecting name and age only
df[['name','age']]

       name  age
101    Ravi   22
102   priya   24
103    Arun   21
104   Sneha   25
105   Kiran   23
106  Anjail   26
107  Vikram   20
108   Meena   27

In [112]:
df[['city','salary']]

          city  salary
101   Hyderbad   30000
102    Chennai   40000
103  Bangalore   28000
104   Hyderbad   50000
105     Mumbai   35000
106    Chennai   45000
107  Bangalore   25000
108     Mumbai   55000

In [113]:
# using to filter interger
df.iloc[0:3]

      name  age       city  salary
101   Ravi   22   Hyderbad   30000
102  priya   24    Chennai   40000
103   Arun   21  Bangalore   28000

In [114]:
# using to filter index
df.loc[102:105]

      name  age       city  salary
102  priya   24    Chennai   40000
103   Arun   21  Bangalore   28000
104  Sneha   25   Hyderbad   50000
105  Kiran   23     Mumbai   35000

In [115]:
df['salary']>45000

101    False
102    False
103    False
104     True
105    False
106    False
107    False
108     True
Name: salary, dtype: bool

In [116]:
df[df['salary']<35000]

       name  age       city  salary
101    Ravi   22   Hyderbad   30000
103    Arun   21  Bangalore   28000
107  Vikram   20  Bangalore   25000

In [117]:
data={
      "student_id":[101,102,103,104,105,106,107,108,109,110],
      "name":['Aarav','Priya','Rahul','Sneha','Arjun',
              'Divya','Kiran','Ananya','Rohit','Meena'],
      "age":[20,21,19,22,20,21,23,19,22,20],
      "course":['python','power bi','python','excel','python',
                'power bi','excel','python','power bi','excel'],
      "marks":[85,78,92,67,88,74,81,95,69,90],
      "attendance":[92,85,96,78,89,82,91,98,75,94],
      "city":['Hyderabad','Chennai','Bangalore','Hyderbad','Pune',
              'Chennai','Hyderbad','Bangalore','Pune','Hyderbad']}

df=pd.DataFrame(data)
# 1
print(df)

   student_id    name  age    course  marks  attendance       city
0         101   Aarav   20    python     85          92  Hyderabad
1         102   Priya   21  power bi     78          85    Chennai
2         103   Rahul   19    python     92          96  Bangalore
3         104   Sneha   22     excel     67          78   Hyderbad
4         105   Arjun   20    python     88          89       Pune
5         106   Divya   21  power bi     74          82    Chennai
6         107   Kiran   23     excel     81          91   Hyderbad
7         108  Ananya   19    python     95          98  Bangalore
8         109   Rohit   22  power bi     69          75       Pune
9         110   Meena   20     excel     90          94   Hyderbad

In [118]:
# 2
df.head(5)

   student_id   name  age    course  marks  attendance       city
0         101  Aarav   20    python     85          92  Hyderabad
1         102  Priya   21  power bi     78          85    Chennai
2         103  Rahul   19    python     92          96  Bangalore
3         104  Sneha   22     excel     67          78   Hyderbad
4         105  Arjun   20    python     88          89       Pune

In [119]:
# 3
df.tail(3)

   student_id    name  age    course  marks  attendance       city
7         108  Ananya   19    python     95          98  Bangalore
8         109   Rohit   22  power bi     69          75       Pune
9         110   Meena   20     excel     90          94   Hyderbad

In [120]:
# 4
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   student_id  10 non-null     int64
 1   name        10 non-null     object
 2   age         10 non-null     int64
 3   course      10 non-null     object
 4   marks       10 non-null     int64
 5   attendance  10 non-null     int64
 6   city        10 non-null     object
dtypes: int64(4), object(3)
memory usage: 692.0+ bytes

In [121]:
# 5
df[['name']]

     name
0   Aarav
1   Priya
2   Rahul
3   Sneha
4   Arjun
5   Divya
6   Kiran
7  Ananya
8   Rohit
9   Meena

In [122]:
# 6
df[['name','course','marks']]

     name    course  marks
0   Aarav    python     85
1   Priya  power bi     78
2   Rahul    python     92
3   Sneha     excel     67
4   Arjun    python     88
5   Divya  power bi     74
6   Kiran     excel     81
7  Ananya    python     95
8   Rohit  power bi     69
9   Meena     excel     90

In [123]:
# 7
df.loc[:10,['student_id','name','age','course','marks','attendance','city']]

   student_id    name  age    course  marks  attendance       city
0         101   Aarav   20    python     85          92  Hyderabad
1         102   Priya   21  power bi     78          85    Chennai
2         103   Rahul   19    python     92          96  Bangalore
3         104   Sneha   22     excel     67          78   Hyderbad
4         105   Arjun   20    python     88          89       Pune
5         106   Divya   21  power bi     74          82    Chennai
6         107   Kiran   23     excel     81          91   Hyderbad
7         108  Ananya   19    python     95          98  Bangalore
8         109   Rohit   22  power bi     69          75       Pune
9         110   Meena   20     excel     90          94   Hyderbad

In [124]:
# 8
df.loc[2:6]

   student_id   name  age    course  marks  attendance       city
2         103  Rahul   19    python     92          96  Bangalore
3         104  Sneha   22     excel     67          78   Hyderbad
4         105  Arjun   20    python     88          89       Pune
5         106  Divya   21  power bi     74          82    Chennai
6         107  Kiran   23     excel     81          91   Hyderbad

In [125]:
# 9
df.loc[1:5,['name','course','marks']]

    name    course  marks
1  Priya  power bi     78
2  Rahul    python     92
3  Sneha     excel     67
4  Arjun    python     88
5  Divya  power bi     74

In [126]:
# 10
df.loc[7,['name','marks','city']]

name        Ananya
marks           95
city     Bangalore
Name: 7, dtype: object

In [127]:
# 11

df.iloc[0:5,0:4]

   student_id   name  age    course
0         101  Aarav   20    python
1         102  Priya   21  power bi
2         103  Rahul   19    python
3         104  Sneha   22     excel
4         105  Arjun   20    python

In [128]:
# 12
df[['name','course','marks']].iloc[2:6]

    name    course  marks
2  Rahul    python     92
3  Sneha     excel     67
4  Arjun    python     88
5  Divya  power bi     74

In [129]:
# 13
df.iloc[-3:]

   student_id    name  age    course  marks  attendance       city
7         108  Ananya   19    python     95          98  Bangalore
8         109   Rohit   22  power bi     69          75       Pune
9         110   Meena   20     excel     90          94   Hyderbad

In [130]:
# 14
df[df['marks']>80]

   student_id    name  age  course  marks  attendance       city
0         101   Aarav   20  python     85          92  Hyderabad
2         103   Rahul   19  python     92          96  Bangalore
4         105   Arjun   20  python     88          89       Pune
6         107   Kiran   23   excel     81          91   Hyderbad
7         108  Ananya   19  python     95          98  Bangalore
9         110   Meena   20   excel     90          94   Hyderbad

In [131]:
# 15
df[df['marks']>80 &(df['attendance']>90)]

   student_id    name  age    course  marks  attendance       city
0         101   Aarav   20    python     85          92  Hyderabad
1         102   Priya   21  power bi     78          85    Chennai
2         103   Rahul   19    python     92          96  Bangalore
3         104   Sneha   22     excel     67          78   Hyderbad
4         105   Arjun   20    python     88          89       Pune
5         106   Divya   21  power bi     74          82    Chennai
6         107   Kiran   23     excel     81          91   Hyderbad
7         108  Ananya   19    python     95          98  Bangalore
8         109   Rohit   22  power bi     69          75       Pune
9         110   Meena   20     excel     90          94   Hyderbad

In [132]:
# Manipulating data
sales=pd.Series([5000,7000,None,9000,8000,10000,None],
index=['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'])
print(sales)

Monday        5000.0
Tuesday       7000.0
Wednesday        NaN
Thursday      9000.0
Friday        8000.0
Saturday     10000.0
Sunday           NaN
dtype: float64

In [133]:
# min value
sales.min()

5000.0

In [134]:
# max value
sales.max()

10000.0

In [135]:
# mean
print(sales.mean())

7800.0

In [136]:
# sum
print(sales.sum())

39000.0

In [137]:
# var
sales.var()

3700000.0

In [138]:
# std
sales.std()

1923.5384061671346

In [139]:
# type of data type
sales.dtype

dtype('float64')

In [140]:
# updatind and insertion of data
sales['Tuesday']=9500
print(sales)

Monday        5000.0
Tuesday       9500.0
Wednesday        NaN
Thursday      9000.0
Friday        8000.0
Saturday     10000.0
Sunday           NaN
dtype: float64

In [141]:
sales['jan']=7800
print(sales)

Monday        5000.0
Tuesday       9500.0
Wednesday        NaN
Thursday      9000.0
Friday        8000.0
Saturday     10000.0
Sunday           NaN
jan           7800.0
dtype: float64

In [142]:
sales=sales.drop('Tuesday')
print(sales)

Monday        5000.0
Wednesday        NaN
Thursday      9000.0
Friday        8000.0
Saturday     10000.0
Sunday           NaN
jan           7800.0
dtype: float64

In [143]:
print(sales+2000)

Monday        7000.0
Wednesday        NaN
Thursday     11000.0
Friday       10000.0
Saturday     12000.0
Sunday           NaN
jan           9800.0
dtype: float64

In [144]:
print(sales*2)

Monday       10000.0
Wednesday        NaN
Thursday     18000.0
Friday       16000.0
Saturday     20000.0
Sunday           NaN
jan          15600.0
dtype: float64

In [145]:
# combine two series
s=pd.Series([1,2,3,4,5])
s1=pd.Series([101,102,103,104,105])
print(s)
print('-'*40)
print(s1)
print('-'*40)
d=pd.concat([s,s1])
e=pd.concat([s,s1],ignore_index=True)

print(d)
print('-'*40)
print(e)

0    1
1    2
2    3
3    4
4    5
dtype: int64
----------------------------------------
0    101
1    102
2    103
3    104
4    105
dtype: int64
----------------------------------------
0      1
1      2
2      3
3      4
4      5
0    101
1    102
2    103
3    104
4    105
dtype: int64
----------------------------------------
0      1
1      2
2      3
3      4
4      5
5    101
6    102
7    103
8    104
9    105
dtype: int64

In [146]:
# updating on dataframe
data={
      'name':['Ravi','priya','Arun','Sneha','Kiran','Anjail','Vikram','Meena'],
      'age':[22,24,21,25,23,26,20,27],
      'city':['Hyderbad','Chennai','Bangalore',
              'Hyderbad','Mumbai','Chennai','Bangalore','Mumbai'],
      'salary':[30000,40000,28000,50000,35000,45000,25000,55000]}

df=pd.DataFrame(data,index=[101,102,103,104,105,106,107,108])
print(df)

       name  age       city  salary
101    Ravi   22   Hyderbad   30000
102   priya   24    Chennai   40000
103    Arun   21  Bangalore   28000
104   Sneha   25   Hyderbad   50000
105   Kiran   23     Mumbai   35000
106  Anjail   26    Chennai   45000
107  Vikram   20  Bangalore   25000
108   Meena   27     Mumbai   55000

In [147]:
print(df['age'].sum())
print(df['age'].mean())
print(df['age'].max())
print(df['age'].min())
print(df['age'].std())
print(df['age'].var())
print(df['age'].count())

188
23.5
27
20
2.449489742783178
6.0
8

In [148]:
print(df['salary'].sum())
print(df['salary'].mean())
print(df['salary'].max())
print(df['salary'].min())
print(df['salary'].std())
print(df['salary'].var())
print(df['salary'].count())

308000
38500.0
55000
25000
10862.780491200216
118000000.0
8

In [149]:
df['Bonus']=df['salary']*0.10
print(df)

       name  age       city  salary   Bonus
101    Ravi   22   Hyderbad   30000  3000.0
102   priya   24    Chennai   40000  4000.0
103    Arun   21  Bangalore   28000  2800.0
104   Sneha   25   Hyderbad   50000  5000.0
105   Kiran   23     Mumbai   35000  3500.0
106  Anjail   26    Chennai   45000  4500.0
107  Vikram   20  Bangalore   25000  2500.0
108   Meena   27     Mumbai   55000  5500.0

In [150]:
df['new salary']=df['salary']+df['Bonus']
print(df)

       name  age       city  salary   Bonus  new salary
101    Ravi   22   Hyderbad   30000  3000.0     33000.0
102   priya   24    Chennai   40000  4000.0     44000.0
103    Arun   21  Bangalore   28000  2800.0     30800.0
104   Sneha   25   Hyderbad   50000  5000.0     55000.0
105   Kiran   23     Mumbai   35000  3500.0     38500.0
106  Anjail   26    Chennai   45000  4500.0     49500.0
107  Vikram   20  Bangalore   25000  2500.0     27500.0
108   Meena   27     Mumbai   55000  5500.0     60500.0

In [151]:
df['age']=df['age']+1
print(df)

       name  age       city  salary   Bonus  new salary
101    Ravi   23   Hyderbad   30000  3000.0     33000.0
102   priya   25    Chennai   40000  4000.0     44000.0
103    Arun   22  Bangalore   28000  2800.0     30800.0
104   Sneha   26   Hyderbad   50000  5000.0     55000.0
105   Kiran   24     Mumbai   35000  3500.0     38500.0
106  Anjail   27    Chennai   45000  4500.0     49500.0
107  Vikram   21  Bangalore   25000  2500.0     27500.0
108   Meena   28     Mumbai   55000  5500.0     60500.0

In [152]:
df['new salary']=df['new salary']+500
print(df)

       name  age       city  salary   Bonus  new salary
101    Ravi   23   Hyderbad   30000  3000.0     33500.0
102   priya   25    Chennai   40000  4000.0     44500.0
103    Arun   22  Bangalore   28000  2800.0     31300.0
104   Sneha   26   Hyderbad   50000  5000.0     55500.0
105   Kiran   24     Mumbai   35000  3500.0     39000.0
106  Anjail   27    Chennai   45000  4500.0     50000.0
107  Vikram   21  Bangalore   25000  2500.0     28000.0
108   Meena   28     Mumbai   55000  5500.0     61000.0

In [153]:
df.loc[df['name']=='priya','city']='Pune'
print(df)

       name  age       city  salary   Bonus  new salary
101    Ravi   23   Hyderbad   30000  3000.0     33500.0
102   priya   25       Pune   40000  4000.0     44500.0
103    Arun   22  Bangalore   28000  2800.0     31300.0
104   Sneha   26   Hyderbad   50000  5000.0     55500.0
105   Kiran   24     Mumbai   35000  3500.0     39000.0
106  Anjail   27    Chennai   45000  4500.0     50000.0
107  Vikram   21  Bangalore   25000  2500.0     28000.0
108   Meena   28     Mumbai   55000  5500.0     61000.0

In [154]:
df['city']=df['city'].replace('Bangalore','Hyderbad')
print(df)

       name  age      city  salary   Bonus  new salary
101    Ravi   23  Hyderbad   30000  3000.0     33500.0
102   priya   25      Pune   40000  4000.0     44500.0
103    Arun   22  Hyderbad   28000  2800.0     31300.0
104   Sneha   26  Hyderbad   50000  5000.0     55500.0
105   Kiran   24    Mumbai   35000  3500.0     39000.0
106  Anjail   27   Chennai   45000  4500.0     50000.0
107  Vikram   21  Hyderbad   25000  2500.0     28000.0
108   Meena   28    Mumbai   55000  5500.0     61000.0

In [155]:
df.loc[df['city']=='Mumbai','salary'] =df['salary']*1.05
print(df)

       name  age      city  salary   Bonus  new salary
101    Ravi   23  Hyderbad   30000  3000.0     33500.0
102   priya   25      Pune   40000  4000.0     44500.0
103    Arun   22  Hyderbad   28000  2800.0     31300.0
104   Sneha   26  Hyderbad   50000  5000.0     55500.0
105   Kiran   24    Mumbai   36750  3500.0     39000.0
106  Anjail   27   Chennai   45000  4500.0     50000.0
107  Vikram   21  Hyderbad   25000  2500.0     28000.0
108   Meena   28    Mumbai   57750  5500.0     61000.0

In [156]:
df.loc[df['salary']<45000,'salary']=60000
print(df)

       name  age      city  salary   Bonus  new salary
101    Ravi   23  Hyderbad   60000  3000.0     33500.0
102   priya   25      Pune   60000  4000.0     44500.0
103    Arun   22  Hyderbad   60000  2800.0     31300.0
104   Sneha   26  Hyderbad   50000  5000.0     55500.0
105   Kiran   24    Mumbai   60000  3500.0     39000.0
106  Anjail   27   Chennai   45000  4500.0     50000.0
107  Vikram   21  Hyderbad   60000  2500.0     28000.0
108   Meena   28    Mumbai   57750  5500.0     61000.0

In [157]:
# deleting on dataframe
# axis=0 (rows)
# axis=1 (column) or column name

df.drop('Bonus',axis=1,inplace=True)
print(df)

       name  age      city  salary  new salary
101    Ravi   23  Hyderbad   60000     33500.0
102   priya   25      Pune   60000     44500.0
103    Arun   22  Hyderbad   60000     31300.0
104   Sneha   26  Hyderbad   50000     55500.0
105   Kiran   24    Mumbai   60000     39000.0
106  Anjail   27   Chennai   45000     50000.0
107  Vikram   21  Hyderbad   60000     28000.0
108   Meena   28    Mumbai   57750     61000.0

In [158]:
df.drop(columns=['salary'],inplace=True)
print(df)

       name  age      city  new salary
101    Ravi   23  Hyderbad     33500.0
102   priya   25      Pune     44500.0
103    Arun   22  Hyderbad     31300.0
104   Sneha   26  Hyderbad     55500.0
105   Kiran   24    Mumbai     39000.0
106  Anjail   27   Chennai     50000.0
107  Vikram   21  Hyderbad     28000.0
108   Meena   28    Mumbai     61000.0

# importing and reading the file
df=pd.read_csv('sales.csv') for reading csv file

df=pd.read_execl('sales.xlsx') for readinng execl

#cleaning data
for missing values isnull(),isna(),isnull().sum(),dropna(),fillna()

In [159]:
# cleaning data handling missing values
sales=pd.Series([5000,7000,None,9000,8000,10000,None],
index=['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'])
print(sales)

Monday        5000.0
Tuesday       7000.0
Wednesday        NaN
Thursday      9000.0
Friday        8000.0
Saturday     10000.0
Sunday           NaN
dtype: float64

In [160]:
# for finding the missing values
sales.isna()

Monday       False
Tuesday      False
Wednesday     True
Thursday     False
Friday       False
Saturday     False
Sunday        True
dtype: bool

In [161]:
# for finding the count the values
sales.isna().sum()

np.int64(2)

In [162]:
# for deleting the missing values
sales.dropna()

Monday       5000.0
Tuesday      7000.0
Thursday     9000.0
Friday       8000.0
Saturday    10000.0
dtype: float64

In [163]:
# for fill the data in the missing values
sales.fillna('no data')

Monday        5000.0
Tuesday       7000.0
Wednesday    no data
Thursday      9000.0
Friday        8000.0
Saturday     10000.0
Sunday       no data
dtype: object

In [164]:
employees={
      "EmpId":[101,102,103,104],
      "Name":['Asha',None,'Meena','Sai'],
      "Department":['Sales','IT','HR',None],
      "Salary":[45000,60000,None,89000]
}
I=[901,902,903,904]
df=pd.DataFrame(employees,index=I)
print(df)

     EmpId   Name Department   Salary
901    101   Asha      Sales  45000.0
902    102   None         IT  60000.0
903    103  Meena         HR      NaN
904    104    Sai       None  89000.0

In [165]:
df.isna()

     EmpId   Name  Department  Salary
901  False  False       False   False
902  False   True       False   False
903  False  False       False    True
904  False  False        True   False

In [166]:
df.isna().sum()

EmpId         0
Name          1
Department    1
Salary        1
dtype: int64

In [167]:
df.fillna({'Name':'unknow','Department':0,'Salary':0})

     EmpId    Name Department   Salary
901    101    Asha      Sales  45000.0
902    102  unknow         IT  60000.0
903    103   Meena         HR      0.0
904    104     Sai          0  89000.0

In [168]:
print(df)

     EmpId   Name Department   Salary
901    101   Asha      Sales  45000.0
902    102   None         IT  60000.0
903    103  Meena         HR      NaN
904    104    Sai       None  89000.0

In [169]:
df['Salary'].fillna(df['Salary'].max())

901    45000.0
902    60000.0
903    89000.0
904    89000.0
Name: Salary, dtype: float64

In [170]:
df['Salary'].fillna(df['Salary'].min())

901    45000.0
902    60000.0
903    45000.0
904    89000.0
Name: Salary, dtype: float64

In [171]:
df['Salary'].fillna(df['Salary'].sum())

901     45000.0
902     60000.0
903    194000.0
904     89000.0
Name: Salary, dtype: float64

In [172]:
df['Salary'].fillna(df['Salary'].mean())

901    45000.000000
902    60000.000000
903    64666.666667
904    89000.000000
Name: Salary, dtype: float64

In [173]:
df['Salary'].fillna(df['Salary'].std())

901    45000.000000
902    60000.000000
903    22368.132093
904    89000.000000
Name: Salary, dtype: float64

In [174]:
df['Salary'].fillna(df['Salary'].var())

901    4.500000e+04
902    6.000000e+04
903    5.003333e+08
904    8.900000e+04
Name: Salary, dtype: float64

In [175]:
df['Salary'].fillna(df['Salary'].median())

901    45000.0
902    60000.0
903    60000.0
904    89000.0
Name: Salary, dtype: float64

In [176]:
employees={
      "EmpId":[101,102,103,104],
      "Name":['Asha',None,'Meena','Sai'],
      "Department":['Sales','IT','HR',None],
      "Salary":[45000,60000,None,89000]
}
I=[901,902,903,904]
df_emp=pd.DataFrame(employees,index=I)
print(df_emp)

     EmpId   Name Department   Salary
901    101   Asha      Sales  45000.0
902    102   None         IT  60000.0
903    103  Meena         HR      NaN
904    104    Sai       None  89000.0

In [177]:
df_emp.head(2)

     EmpId  Name Department   Salary
901    101  Asha      Sales  45000.0
902    102  None         IT  60000.0

In [178]:
df_emp.tail(2)

     EmpId   Name Department   Salary
903    103  Meena         HR      NaN
904    104    Sai       None  89000.0

In [179]:
df_emp[['Name','Salary']]

      Name   Salary
901   Asha  45000.0
902   None  60000.0
903  Meena      NaN
904    Sai  89000.0

In [180]:
df_emp[df_emp['EmpId']==103]

     EmpId   Name Department  Salary
903    103  Meena         HR     NaN

In [181]:
df_emp[df_emp['Salary']>50000]

     EmpId  Name Department   Salary
902    102  None         IT  60000.0
904    104   Sai       None  89000.0

In [182]:
df_emp[df_emp['Department']=='It']

Empty DataFrame
Columns: [EmpId, Name, Department, Salary]
Index: []

In [183]:
df_emp['Name'].isna()

901    False
902     True
903    False
904    False
Name: Name, dtype: bool

In [184]:
df_emp['Department'].isna()

901    False
902    False
903    False
904     True
Name: Department, dtype: bool

In [185]:
df_emp.isna().sum()

EmpId         0
Name          1
Department    1
Salary        1
dtype: int64

In [186]:
df_emp.fillna({'Name':'unknown','Department':'Not Assigned'})

     EmpId     Name    Department   Salary
901    101     Asha         Sales  45000.0
902    102  unknown            IT  60000.0
903    103    Meena            HR      NaN
904    104      Sai  Not Assigned  89000.0

In [187]:
df_emp['Bonus']=df_emp['Salary']*0.10
print(df_emp)

     EmpId   Name Department   Salary   Bonus
901    101   Asha      Sales  45000.0  4500.0
902    102   None         IT  60000.0  6000.0
903    103  Meena         HR      NaN     NaN
904    104    Sai       None  89000.0  8900.0

In [188]:
df.loc[df['Name']=='Sai','Salary']=95000
print(df)

     EmpId   Name Department   Salary
901    101   Asha      Sales  45000.0
902    102   None         IT  60000.0
903    103  Meena         HR      NaN
904    104    Sai       None  95000.0

In [189]:
df_emp.rename(columns={'EmpId':'EmployeeID'})

     EmployeeID   Name Department   Salary   Bonus
901         101   Asha      Sales  45000.0  4500.0
902         102   None         IT  60000.0  6000.0
903         103  Meena         HR      NaN     NaN
904         104    Sai       None  89000.0  8900.0

group-by

df.groupby('column name').['age'].mean()

In [190]:
employees={
      "EmpId":[101,102,103,104],
      "Name":['Asha',None,'Meena','Sai'],
      "Department":['Sales','IT','HR',None],
      "Salary":[45000,60000,None,89000]
}
I=[901,902,903,904]
df_emp=pd.DataFrame(employees,index=I)
print(df_emp)

     EmpId   Name Department   Salary
901    101   Asha      Sales  45000.0
902    102   None         IT  60000.0
903    103  Meena         HR      NaN
904    104    Sai       None  89000.0

In [191]:
df_emp=df_emp.fillna({'Name':'Tony','Department':'IT','Salary':50000})
print(df_emp)

     EmpId   Name Department   Salary
901    101   Asha      Sales  45000.0
902    102   Tony         IT  60000.0
903    103  Meena         HR  50000.0
904    104    Sai         IT  89000.0

In [192]:
df_emp.groupby('Department')['Salary'].mean()
df_emp.groupby('Department')['Salary'].max()
df_emp.groupby('Department')['Salary'].min()

Department
HR       50000.0
IT       60000.0
Sales    45000.0
Name: Salary, dtype: float64

In [193]:
print(df_emp.groupby('Department')['Salary'].max())

Department
HR       50000.0
IT       89000.0
Sales    45000.0
Name: Salary, dtype: float64

In [194]:
df_emp.groupby('Department')['Salary'].min()

Department
HR       50000.0
IT       60000.0
Sales    45000.0
Name: Salary, dtype: float64

In [195]:
df_emp.groupby('Department')['Salary'].std()

Department
HR                NaN
IT       20506.096654
Sales             NaN
Name: Salary, dtype: float64

In [196]:
df_emp.groupby('Department')['Salary'].agg(['mean','max','min'])

               mean      max      min
Department
HR          50000.0  50000.0  50000.0
IT          74500.0  89000.0  60000.0
Sales       45000.0  45000.0  45000.0

In [197]:
import pandas as pd
data = {
    "Name" : ["ravi","priya","Arun","sneha","kiran","Anjali","vikram","Meena"],
    "Age" : [22,24,21,25,23,26,20,27],
    "City" : ["Hyderabad","chennai","Banglore","Hydrerabad",
              "Mumbai","chennai","Banglore","Mumbai"],
    "Salary" : [30000,40000,28000,50000,35000,45000,25000,55000]
}
df = pd.DataFrame(data,index = [101,102,103,104,105,106,107,108])

In [198]:
print(df)

       Name  Age        City  Salary
101    ravi   22   Hyderabad   30000
102   priya   24     chennai   40000
103    Arun   21    Banglore   28000
104   sneha   25  Hydrerabad   50000
105   kiran   23      Mumbai   35000
106  Anjali   26     chennai   45000
107  vikram   20    Banglore   25000
108   Meena   27      Mumbai   55000

In [199]:
print(df[['Name', 'Salary']])

       Name  Salary
101    ravi   30000
102   priya   40000
103    Arun   28000
104   sneha   50000
105   kiran   35000
106  Anjali   45000
107  vikram   25000
108   Meena   55000

In [200]:
df.loc[df['Age']>23]

       Name  Age        City  Salary
102   priya   24     chennai   40000
104   sneha   25  Hydrerabad   50000
106  Anjali   26     chennai   45000
108   Meena   27      Mumbai   55000

In [201]:
df.loc[df['Salary']>40000]

       Name  Age        City  Salary
104   sneha   25  Hydrerabad   50000
106  Anjali   26     chennai   45000
108   Meena   27      Mumbai   55000

In [202]:
df.loc[df['City']=='chennai']

       Name  Age     City  Salary
102   priya   24  chennai   40000
106  Anjali   26  chennai   45000

In [203]:
df.loc[(df['Age']>22) & (df['Salary']>35000)]

       Name  Age        City  Salary
102   priya   24     chennai   40000
104   sneha   25  Hydrerabad   50000
106  Anjali   26     chennai   45000
108   Meena   27      Mumbai   55000

In [205]:
df.loc[(df['City'] == 'Mumbai') | (df['City'] == 'Banglore')]

       Name  Age      City  Salary
103    Arun   21  Banglore   28000
105   kiran   23    Mumbai   35000
107  vikram   20  Banglore   25000
108   Meena   27    Mumbai   55000

In [208]:
df.loc[df['Salary']>35000,['Name','Salary']]

       Name  Salary
102   priya   40000
104   sneha   50000
106  Anjali   45000
108   Meena   55000

In [209]:
df.loc[102:104]

      Name  Age        City  Salary
102  priya   24     chennai   40000
103   Arun   21    Banglore   28000
104  sneha   25  Hydrerabad   50000