handling duplicate values

df.duplicated() for find the duplicate row

df.duplicated(keep=False)To find all rows which are invloved

By default keep will be in True

In [109]:
import pandas as pd
data = {
    "EmpID":[101,102,103,104,105,106,107,108,109,110,110],
    "Name":['Ravi','PRIYA','Arun','sneha','Kiran','ANJALI','Vikram',
  'meena','RAHUL',
      'Sneha','Sneha'],
    "City":["Hyderabad","hyderabad","CHENNAI","Chennai",
    "Banglore","BANGLORE",
        'Mumbai','mumbai','Delhi','Hyderabad','Hyderabad'],
    "Salary":[30000,
    4000,3500,4500,32000,5000,38000,42000,36000,45000,45000]
}
df=pd.DataFrame(data)
print(df)

    EmpID    Name       City  Salary
0     101    Ravi  Hyderabad   30000
1     102   PRIYA  hyderabad    4000
2     103    Arun    CHENNAI    3500
3     104   sneha    Chennai    4500
4     105   Kiran   Banglore   32000
5     106  ANJALI   BANGLORE    5000
6     107  Vikram     Mumbai   38000
7     108   meena     mumbai   42000
8     109   RAHUL      Delhi   36000
9     110   Sneha  Hyderabad   45000
10    110   Sneha  Hyderabad   45000

In [110]:
df.duplicated()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10     True
dtype: bool

In [111]:
print(df[df.duplicated()])

    EmpID   Name       City  Salary
10    110  Sneha  Hyderabad   45000

In [112]:
d=df[df.duplicated(keep=False)] # to print both original and duplicate value
print(d)

    EmpID   Name       City  Salary
9     110  Sneha  Hyderabad   45000
10    110  Sneha  Hyderabad   45000

In [113]:
count=df.duplicated().sum()
print(count)

1

In [114]:
duplicate_rows = df[df.duplicated()]
total = duplicate_rows['Salary'].sum()
print(total)

45000

In [115]:
duplicate_rows = df[df.duplicated()]
total = duplicate_rows[['Name','Salary']].sum()
print(total)

Name      Sneha
Salary    45000
dtype: object

In [116]:
duplicate_rows = df[df.duplicated(keep=False)]
print(duplicate_rows)

    EmpID   Name       City  Salary
9     110  Sneha  Hyderabad   45000
10    110  Sneha  Hyderabad   45000

In [117]:
df['EmpID'].duplicated()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10     True
Name: EmpID, dtype: bool

In [118]:
f=df['Name'].duplicated() #storing
print(f)

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10     True
Name: Name, dtype: bool

In [119]:
# To drop the duplicates we use df=df.drop_duplcates()
df.drop_duplicates()

print(df)

    EmpID    Name       City  Salary
0     101    Ravi  Hyderabad   30000
1     102   PRIYA  hyderabad    4000
2     103    Arun    CHENNAI    3500
3     104   sneha    Chennai    4500
4     105   Kiran   Banglore   32000
5     106  ANJALI   BANGLORE    5000
6     107  Vikram     Mumbai   38000
7     108   meena     mumbai   42000
8     109   RAHUL      Delhi   36000
9     110   Sneha  Hyderabad   45000
10    110   Sneha  Hyderabad   45000

In [120]:
print(df)

    EmpID    Name       City  Salary
0     101    Ravi  Hyderabad   30000
1     102   PRIYA  hyderabad    4000
2     103    Arun    CHENNAI    3500
3     104   sneha    Chennai    4500
4     105   Kiran   Banglore   32000
5     106  ANJALI   BANGLORE    5000
6     107  Vikram     Mumbai   38000
7     108   meena     mumbai   42000
8     109   RAHUL      Delhi   36000
9     110   Sneha  Hyderabad   45000
10    110   Sneha  Hyderabad   45000

In [121]:
df.drop_duplicates(keep='last')

    EmpID    Name       City  Salary
0     101    Ravi  Hyderabad   30000
1     102   PRIYA  hyderabad    4000
2     103    Arun    CHENNAI    3500
3     104   sneha    Chennai    4500
4     105   Kiran   Banglore   32000
5     106  ANJALI   BANGLORE    5000
6     107  Vikram     Mumbai   38000
7     108   meena     mumbai   42000
8     109   RAHUL      Delhi   36000
10    110   Sneha  Hyderabad   45000

In [122]:
df.drop_duplicates(keep='first')

   EmpID    Name       City  Salary
0    101    Ravi  Hyderabad   30000
1    102   PRIYA  hyderabad    4000
2    103    Arun    CHENNAI    3500
3    104   sneha    Chennai    4500
4    105   Kiran   Banglore   32000
5    106  ANJALI   BANGLORE    5000
6    107  Vikram     Mumbai   38000
7    108   meena     mumbai   42000
8    109   RAHUL      Delhi   36000
9    110   Sneha  Hyderabad   45000

In [123]:
# remove all occurrences of duplicates
df.drop_duplicates(keep=False)

   EmpID    Name       City  Salary
0    101    Ravi  Hyderabad   30000
1    102   PRIYA  hyderabad    4000
2    103    Arun    CHENNAI    3500
3    104   sneha    Chennai    4500
4    105   Kiran   Banglore   32000
5    106  ANJALI   BANGLORE    5000
6    107  Vikram     Mumbai   38000
7    108   meena     mumbai   42000
8    109   RAHUL      Delhi   36000

In [124]:

data = {
   "TransactionID": [1001, 1002, 1003, 1004, 1005,
                      1006, 1007, 1008, 1009, 1010, 1010, 1011],
   "Customer": ["Ravi", "Priya", "Arun", "Sneha", "Kiran",
                "Anjali", "Vikram", "Meena", "Rahul", "Sneha",
                "Sneha", "Kiran"],
   "Product": ["Laptop", "Mobile", "Tablet", "Headphones", "Mouse",
               "Keyboard", "Monitor", "Laptop", "Mobile", "Headphones",
               "Headphones", "Mouse"],
   "Amount": [55000, 25000, 30000, 5000, 1500,
              2500, 18000, 55000, 22000, 5000,
              5000, 1500]}
df_sales = pd.DataFrame(data)
print(df_sales)

    TransactionID Customer     Product  Amount
0            1001     Ravi      Laptop   55000
1            1002    Priya      Mobile   25000
2            1003     Arun      Tablet   30000
3            1004    Sneha  Headphones    5000
4            1005    Kiran       Mouse    1500
5            1006   Anjali    Keyboard    2500
6            1007   Vikram     Monitor   18000
7            1008    Meena      Laptop   55000
8            1009    Rahul      Mobile   22000
9            1010    Sneha  Headphones    5000
10           1010    Sneha  Headphones    5000
11           1011    Kiran       Mouse    1500

In [125]:
# 1
df_sales[df_sales.duplicated()]

    TransactionID Customer     Product  Amount
10           1010    Sneha  Headphones    5000

In [126]:
# 2
count=df_sales.duplicated().sum()
print(count)

1

In [127]:
# 3
duplicate_sales=df_sales[df_sales.duplicated(keep=False)]
print(duplicate_sales)

    TransactionID Customer     Product  Amount
9            1010    Sneha  Headphones    5000
10           1010    Sneha  Headphones    5000

In [128]:
# 4
ds=df_sales[df_sales.duplicated(keep=False)]
total=ds['Amount'].sum()
print(total)

10000

In [129]:
# 5
ds=df_sales[df_sales.duplicated(keep=False)]
t=ds['TransactionID'].count()
print(t)

2

In [130]:
# 6
df_sales[df_sales['Customer'].duplicated(keep=False)]

    TransactionID Customer     Product  Amount
3            1004    Sneha  Headphones    5000
4            1005    Kiran       Mouse    1500
9            1010    Sneha  Headphones    5000
10           1010    Sneha  Headphones    5000
11           1011    Kiran       Mouse    1500

In [131]:
# 7
df_sales.drop_duplicates(keep='first')

    TransactionID Customer     Product  Amount
0            1001     Ravi      Laptop   55000
1            1002    Priya      Mobile   25000
2            1003     Arun      Tablet   30000
3            1004    Sneha  Headphones    5000
4            1005    Kiran       Mouse    1500
5            1006   Anjali    Keyboard    2500
6            1007   Vikram     Monitor   18000
7            1008    Meena      Laptop   55000
8            1009    Rahul      Mobile   22000
9            1010    Sneha  Headphones    5000
11           1011    Kiran       Mouse    1500

In [132]:
# 8
df_sales['TransactionID'].drop_duplicates()

0     1001
1     1002
2     1003
3     1004
4     1005
5     1006
6     1007
7     1008
8     1009
9     1010
11    1011
Name: TransactionID, dtype: int64

In [133]:
# 9
df_sales[['Customer','Product']].drop_duplicates()

  Customer     Product
0     Ravi      Laptop
1    Priya      Mobile
2     Arun      Tablet
3    Sneha  Headphones
4    Kiran       Mouse
5   Anjali    Keyboard
6   Vikram     Monitor
7    Meena      Laptop
8    Rahul      Mobile

In [147]:
# 10
df_sales.drop_duplicates(['TransactionID'],keep='first',inplace=True)
print(df_sales)

    TransactionID Customer     Product  Amount
0            1001     Ravi      Laptop   55000
1            1002    Priya      Mobile   25000
2            1003     Arun      Tablet   30000
3            1004    Sneha  Headphones    5000
4            1005    Kiran       Mouse    1500
5            1006   Anjali    Keyboard    2500
6            1007   Vikram     Monitor   18000
7            1008    Meena      Laptop   55000
8            1009    Rahul      Mobile   22000
9            1010    Sneha  Headphones    5000
11           1011    Kiran       Mouse    1500

In [135]:
data = {
   "VisitID": [501, 502, 503, 504, 505,
               506, 507, 508, 509, 510, 510, 511],
   "Patient": ["Rahul", "Anita", "Suresh", "Priya", "Kiran",
               "Anjali", "Ravi", "Meena", "Arun", "Priya",
               "Priya", "Kiran"],
   "Department": ["Cardiology", "Neurology", "Orthopedic", "General",
                  "Dental", "Cardiology", "Neurology", "General",
                  "Dental", "Cardiology", "Cardiology", "Dental"],
   "BillAmount": [5000, 7500, 4500, 2000, 1500,
                  6000, 7000, 2500, 1800, 6000,6000, 1500]}
df = pd.DataFrame(data)
print(df)

    VisitID Patient  Department  BillAmount
0       501   Rahul  Cardiology        5000
1       502   Anita   Neurology        7500
2       503  Suresh  Orthopedic        4500
3       504   Priya     General        2000
4       505   Kiran      Dental        1500
5       506  Anjali  Cardiology        6000
6       507    Ravi   Neurology        7000
7       508   Meena     General        2500
8       509    Arun      Dental        1800
9       510   Priya  Cardiology        6000
10      510   Priya  Cardiology        6000
11      511   Kiran      Dental        1500

In [136]:
# 1
df[df.duplicated(keep=False)]

    VisitID Patient  Department  BillAmount
9       510   Priya  Cardiology        6000
10      510   Priya  Cardiology        6000

In [137]:
# 2
count=df.duplicated().sum()
print(count)

1

In [138]:
# 3
df[df.duplicated(keep='first')]

    VisitID Patient  Department  BillAmount
10      510   Priya  Cardiology        6000

In [139]:
# 4
total=df.loc[df.duplicated(keep=False),'BillAmount'].sum()
print(total)

12000

In [140]:
# 5
visit=df[df['VisitID'].duplicated(keep=False)]
print(visit)

    VisitID Patient  Department  BillAmount
9       510   Priya  Cardiology        6000
10      510   Priya  Cardiology        6000

In [141]:
# 6
df[df['Patient'].duplicated(keep=False)]

    VisitID Patient  Department  BillAmount
3       504   Priya     General        2000
4       505   Kiran      Dental        1500
9       510   Priya  Cardiology        6000
10      510   Priya  Cardiology        6000
11      511   Kiran      Dental        1500

In [142]:
# 7
df.drop_duplicates(keep='first')

    VisitID Patient  Department  BillAmount
0       501   Rahul  Cardiology        5000
1       502   Anita   Neurology        7500
2       503  Suresh  Orthopedic        4500
3       504   Priya     General        2000
4       505   Kiran      Dental        1500
5       506  Anjali  Cardiology        6000
6       507    Ravi   Neurology        7000
7       508   Meena     General        2500
8       509    Arun      Dental        1800
9       510   Priya  Cardiology        6000
11      511   Kiran      Dental        1500

In [143]:
# 8
df['VisitID'].drop_duplicates()

0     501
1     502
2     503
3     504
4     505
5     506
6     507
7     508
8     509
9     510
11    511
Name: VisitID, dtype: int64

In [144]:
# 9
df[['Patient','Department']].drop_duplicates()

  Patient  Department
0   Rahul  Cardiology
1   Anita   Neurology
2  Suresh  Orthopedic
3   Priya     General
4   Kiran      Dental
5  Anjali  Cardiology
6    Ravi   Neurology
7   Meena     General
8    Arun      Dental
9   Priya  Cardiology

In [151]:
# 10
df.drop_duplicates(['VisitID'],keep='first',inplace=True)
print(df)

    VisitID Patient  Department  BillAmount
0       501   Rahul  Cardiology        5000
1       502   Anita   Neurology        7500
2       503  Suresh  Orthopedic        4500
3       504   Priya     General        2000
4       505   Kiran      Dental        1500
5       506  Anjali  Cardiology        6000
6       507    Ravi   Neurology        7000
7       508   Meena     General        2500
8       509    Arun      Dental        1800
9       510   Priya  Cardiology        6000
11      511   Kiran      Dental        1500