In [ ]:
import pandas as pd
# title() used to converts the first character of each word to uppercase
t='tony stark'
print(t.title())

Tony Stark

In [ ]:
# example
df=pd.DataFrame({
    'City':['  new york ','CHICAGO','los angles ','   houston']
}
)
print('---- Before ----')
print(df)

---- Before ----
          City
0    new york
1      CHICAGO
2  los angles
3      houston

In [ ]:
df['City'].str.title()

0      New York
1        Chicago
2    Los Angles
3        Houston
Name: City, dtype: object

In [ ]:
df['City'].str.strip()

0      new york
1       CHICAGO
2    los angles
3       houston
Name: City, dtype: object

In [ ]:
# copy() method
data={
    'Name':['ravi','priya','arun','sneha'],
    'Age':[22,24,21,25],
    'Salary':[30000,40000,28000,50000]
}
df=pd.DataFrame(data)
print(df)

    Name  Age  Salary
0   ravi   22   30000
1  priya   24   40000
2   arun   21   28000
3  sneha   25   50000

In [ ]:
d1=df.copy()
print(d1)

    Name  Age  Salary
0   ravi   22   30000
1  priya   24   40000
2   arun   21   28000
3  sneha   25   50000

In [ ]:
d1['Name']=d1['Name'].str.strip().str.title()
print('original data')
print(df)
print('copied data')
print(d1)

original data
    Name  Age  Salary
0   ravi   22   30000
1  priya   24   40000
2   arun   21   28000
3  sneha   25   50000
copied data
    Name  Age  Salary
0   Ravi   22   30000
1  Priya   24   40000
2   Arun   21   28000
3  Sneha   25   50000

In [ ]:
df_deep=df.copy(deep=True)
df_deep.loc[0,'Salary']=50000
print('original data')
print(df)
print('deep copy')
print(df_deep)

original data
    Name  Age  Salary
0   ravi   22   30000
1  priya   24   40000
2   arun   21   28000
3  sneha   25   50000
deep copy
    Name  Age  Salary
0   ravi   22   50000
1  priya   24   40000
2   arun   21   28000
3  sneha   25   50000

In [ ]:
df_shallow=df.copy(deep=False)
df_shallow.loc[2,'Age']=20
print('original data')
print(df)
print('shallow copy')
print(df_shallow)

original data
    Name  Age  Salary
0   ravi   22   30000
1  priya   24   40000
2   arun   20   28000
3  sneha   25   50000
shallow copy
    Name  Age  Salary
0   ravi   22   30000
1  priya   24   40000
2   arun   20   28000
3  sneha   25   50000