In [ ]:
# Merging & Joining
import pandas as pd
df1 = pd.DataFrame({
    'ID': [1, 2, 3],
    'Name': ['A', 'B', 'C']
})

df2 = pd.DataFrame({
    'ID': [1, 2, 4],
    'Salary': [100, 200, 300]
})

In [ ]:
merged = pd.merge(
    df1,
    df2,
    on='ID',
    how='inner')
print(merged)

   ID Name  Salary
0   1    A     100
1   2    B     200

In [ ]:
# outer
m1 = pd.merge(
    df1,
    df2,
    on='ID',
    how='outer'
)
print(m1)

   ID Name  Salary
0   1    A   100.0
1   2    B   200.0
2   3    C     NaN
3   4  NaN   300.0

In [ ]:
# right
m2 = pd.merge(
    df1,
    df2,
    on='ID',
    how='right'
)
print(m2)

   ID Name  Salary
0   1    A     100
1   2    B     200
2   4  NaN     300

In [ ]:
# left
m3 = pd.merge(
    df1,
    df2,
    on='ID',
    how='left'
)
print(m3)

   ID Name  Salary
0   1    A   100.0
1   2    B   200.0
2   3    C     NaN

In [ ]:
# pd.concat() for rows
combined = pd.concat(
    [df1, df2],
    axis=0,
    ignore_index=True
)
print(combined)

   ID Name  Salary
0   1    A     NaN
1   2    B     NaN
2   3    C     NaN
3   1  NaN   100.0
4   2  NaN   200.0
5   4  NaN   300.0

In [ ]:
# for columns
c1 = pd.concat([df1, df2],axis=1,ignore_index=True)
print(c1)

   0  1  2    3
0  1  A  1  100
1  2  B  2  200
2  3  C  4  300

In [ ]:
# pandas - Merging & Joining practice
import pandas as pd

df1 = pd.DataFrame({
    "ID": [101, 102, 103, 104, 105],
    "Name": ["Rahul", "Priya", "Arjun", "Sneha", "Kiran"]
})

print(df1)

print("-"*25)

df2 = pd.DataFrame({
    "ID": [101, 102, 103, 104, 105],
    "Marks": [85, 92, 78, 88, 95]
})

print(df2)

    ID   Name
0  101  Rahul
1  102  Priya
2  103  Arjun
3  104  Sneha
4  105  Kiran
-------------------------
    ID  Marks
0  101     85
1  102     92
2  103     78
3  104     88
4  105     95

In [ ]:
df=pd.DataFrame({
    "Emp_ID":[101,102,103,104,105],
    "Name":['Ravi','Priya','Arjun','Sneha','Kiran'],
    "Department":['IT','HR','Sales','IT','Finance']
})

dd=pd.DataFrame({
        "Emp_ID":[101,102,103,106,107],
        "Salary":[50000,45000,55000,60000,48000],
        "Bonus":[5000,4000,6000,7000,3500]

})
print(df)
print("-"*30)
print(dd)

   Emp_ID   Name Department
0     101   Ravi         IT
1     102  Priya         HR
2     103  Arjun      Sales
3     104  Sneha         IT
4     105  Kiran    Finance
------------------------------
   Emp_ID  Salary  Bonus
0     101   50000   5000
1     102   45000   4000
2     103   55000   6000
3     106   60000   7000
4     107   48000   3500

In [ ]:
m=pd.merge(df,dd,on='Emp_ID',how='outer')
print(m)

   Emp_ID   Name Department   Salary   Bonus
0     101   Ravi         IT  50000.0  5000.0
1     102  Priya         HR  45000.0  4000.0
2     103  Arjun      Sales  55000.0  6000.0
3     104  Sneha         IT      NaN     NaN
4     105  Kiran    Finance      NaN     NaN
5     106    NaN        NaN  60000.0  7000.0
6     107    NaN        NaN  48000.0  3500.0

In [ ]:
m1=pd.merge(df,dd,on='Emp_ID',how='inner')
print(m1)

   Emp_ID   Name Department  Salary  Bonus
0     101   Ravi         IT   50000   5000
1     102  Priya         HR   45000   4000
2     103  Arjun      Sales   55000   6000

In [ ]:
m2=pd.merge(df,dd,on='Emp_ID',how='right')
print(m2)

   Emp_ID   Name Department  Salary  Bonus
0     101   Ravi         IT   50000   5000
1     102  Priya         HR   45000   4000
2     103  Arjun      Sales   55000   6000
3     106    NaN        NaN   60000   7000
4     107    NaN        NaN   48000   3500

In [ ]:
m3=pd.merge(df,dd,on='Emp_ID',how='inner')
print(m3)

   Emp_ID   Name Department  Salary  Bonus
0     101   Ravi         IT   50000   5000
1     102  Priya         HR   45000   4000
2     103  Arjun      Sales   55000   6000

In [ ]:
pd.concat([df,dd],axis=0,ignore_index=True)

   Emp_ID   Name Department   Salary   Bonus
0     101   Ravi         IT      NaN     NaN
1     102  Priya         HR      NaN     NaN
2     103  Arjun      Sales      NaN     NaN
3     104  Sneha         IT      NaN     NaN
4     105  Kiran    Finance      NaN     NaN
5     101    NaN        NaN  50000.0  5000.0
6     102    NaN        NaN  45000.0  4000.0
7     103    NaN        NaN  55000.0  6000.0
8     106    NaN        NaN  60000.0  7000.0
9     107    NaN        NaN  48000.0  3500.0

In [ ]:
# day 13
# apply()

import pandas as pd
dept_data= {
      "Department":['IT','HR','Finance','Sales'],
      "Salary":[35000,42000,48000,55000],
      "Location":['Hyderabad','Bangalore','Chennai','Delhi']
}
dept_df=pd.DataFrame(dept_data)
dept_df

  Department  Salary   Location
0         IT   35000  Hyderabad
1         HR   42000  Bangalore
2    Finance   48000    Chennai
3      Sales   55000      Delhi

In [ ]:
dept_df['Bonus']=dept_df['Salary'].apply(lambda x:x*0.10)
dept_df

  Department  Salary   Location   Bonus
0         IT   35000  Hyderabad  3500.0
1         HR   42000  Bangalore  4200.0
2    Finance   48000    Chennai  4800.0
3      Sales   55000      Delhi  5500.0

In [ ]:
city_code={
    "Hyderabad":'HYD',
    "Bangalore":'BLR',
    "Chennai":'CHE',
    "Delhi":'DEL'
}
dept_df['city_code']=dept_df['Location'].map(city_code)
dept_df

  Department  Salary   Location   Bonus city_code
0         IT   35000  Hyderabad  3500.0       HYD
1         HR   42000  Bangalore  4200.0       BLR
2    Finance   48000    Chennai  4800.0       CHE
3      Sales   55000      Delhi  5500.0       DEL