In [2]:
import pandas as pd
data={
    'Date':[
        '2025-01-01',
        '2025-01-02',
        '2025-01-03',
        '2025-01-04',
        '2025-01-05'
    ],
    "Sales":[5000,6500,4200,7000,5500]
}
df=pd.DataFrame(data)
print(df)
df.dtypes

         Date  Sales
0  2025-01-01   5000
1  2025-01-02   6500
2  2025-01-03   4200
3  2025-01-04   7000
4  2025-01-05   5500

Date     object
Sales     int64
dtype: object

In [4]:
# pd.to_datatime() is used converts values into pandas datatime format
df['Date']=pd.to_datetime(df['Date'])
df.dtypes

Date     datetime64[ns]
Sales             int64
dtype: object

In [7]:
# pd.data_range is used to show specifying and end data with no of periods
dates=pd.date_range(
    start='2025-01-01',
    periods=10
)
print(dates)

DatetimeIndex(['2025-01-01', '2025-01-02', '2025-01-03', '2025-01-04',
               '2025-01-05', '2025-01-06', '2025-01-07', '2025-01-08',
               '2025-01-09', '2025-01-10'],
              dtype='datetime64[ns]', freq='D')

In [12]:
# Generating Data with Frequency
'''
freq='D' is used of Day
freq='H' is used for hourly
freq='min' is used for minute
freq='MS' is used month starting
freq='ME' is used month ending
freq='YS' is used year starting
freq='YE' is used year ending
'''
dates = pd.date_range(start="2025-01-01",periods=10,freq="D")
print(dates)

DatetimeIndex(['2025-01-01', '2025-01-02', '2025-01-03', '2025-01-04',
               '2025-01-05', '2025-01-06', '2025-01-07', '2025-01-08',
               '2025-01-09', '2025-01-10'],
              dtype='datetime64[ns]', freq='D')

In [15]:
dates=pd.date_range(start='2025-01-01',periods=10,freq='H')
print(dates)

DatetimeIndex(['2025-01-01 00:00:00', '2025-01-01 01:00:00',
               '2025-01-01 02:00:00', '2025-01-01 03:00:00',
               '2025-01-01 04:00:00', '2025-01-01 05:00:00',
               '2025-01-01 06:00:00', '2025-01-01 07:00:00',
               '2025-01-01 08:00:00', '2025-01-01 09:00:00'],
              dtype='datetime64[ns]', freq='h')

/tmp/ipykernel_1264/1273677623.py:1: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  dates=pd.date_range(start='2025-01-01',periods=10,freq='H')

In [16]:
dates=pd.date_range(start='2025-01-01',periods=10,freq='min')
print(dates)

DatetimeIndex(['2025-01-01 00:00:00', '2025-01-01 00:01:00',
               '2025-01-01 00:02:00', '2025-01-01 00:03:00',
               '2025-01-01 00:04:00', '2025-01-01 00:05:00',
               '2025-01-01 00:06:00', '2025-01-01 00:07:00',
               '2025-01-01 00:08:00', '2025-01-01 00:09:00'],
              dtype='datetime64[ns]', freq='min')

In [17]:
dates=pd.date_range(start='2025-01-01',periods=10,freq='MS')
print(dates)

DatetimeIndex(['2025-01-01', '2025-02-01', '2025-03-01', '2025-04-01',
               '2025-05-01', '2025-06-01', '2025-07-01', '2025-08-01',
               '2025-09-01', '2025-10-01'],
              dtype='datetime64[ns]', freq='MS')

In [18]:
dates=pd.date_range(start='2025-01-01',periods=10,freq='ME')
print(dates)

DatetimeIndex(['2025-01-31', '2025-02-28', '2025-03-31', '2025-04-30',
               '2025-05-31', '2025-06-30', '2025-07-31', '2025-08-31',
               '2025-09-30', '2025-10-31'],
              dtype='datetime64[ns]', freq='ME')

In [25]:
dates=pd.date_range(start='2025-01-01',periods=10,freq='YS')
print(dates)

DatetimeIndex(['2025-01-01', '2026-01-01', '2027-01-01', '2028-01-01',
               '2029-01-01', '2030-01-01', '2031-01-01', '2032-01-01',
               '2033-01-01', '2034-01-01'],
              dtype='datetime64[ns]', freq='YS-JAN')

In [26]:
dates=pd.date_range(start='2025-01-01',periods=10,freq='YE')
print(dates)

DatetimeIndex(['2025-12-31', '2026-12-31', '2027-12-31', '2028-12-31',
               '2029-12-31', '2030-12-31', '2031-12-31', '2032-12-31',
               '2033-12-31', '2034-12-31'],
              dtype='datetime64[ns]', freq='YE-DEC')

In [30]:
# Filtering Based on Year
df["Date"].dt.year

0    2025
1    2025
2    2025
3    2025
4    2025
Name: Date, dtype: int32

In [33]:
df["Year"] = df["Date"].dt.year
print(df)

        Date  Sales  Year
0 2025-01-01   5000  2025
1 2025-01-02   6500  2025
2 2025-01-03   4200  2025
3 2025-01-04   7000  2025
4 2025-01-05   5500  2025

In [34]:
# Month Name
df["Date"].dt.month_name()

0    January
1    January
2    January
3    January
4    January
Name: Date, dtype: object

In [35]:
# Day of Week
df["Date"].dt.day_name()

0    Wednesday
1     Thursday
2       Friday
3     Saturday
4       Sunday
Name: Date, dtype: object

In [36]:
df = pd.DataFrame({
    "DateTime": pd.to_datetime([
        "2025-01-01 08:30:15",
        "2025-01-01 10:45:20",
        "2025-01-01 14:20:30",
        "2025-01-01 18:10:45"
    ]),
    "Sales": [2000, 3500, 5000, 4200]
})
df["DateTime"].dt.hour

0     8
1    10
2    14
3    18
Name: DateTime, dtype: int32

In [37]:
df["DateTime"].dt.minute

0    30
1    45
2    20
3    10
Name: DateTime, dtype: int32

In [38]:
df[
    (df["DateTime"].dt.hour >= 10) &
    (df["DateTime"].dt.hour <= 14)
]

             DateTime  Sales
1 2025-01-01 10:45:20   3500
2 2025-01-01 14:20:30   5000

In [39]:
df[df["DateTime"].dt.minute == 45]

             DateTime  Sales
1 2025-01-01 10:45:20   3500

In [40]:
df["DateTime"].dt.second

0    15
1    20
2    30
3    45
Name: DateTime, dtype: int32

In [41]:
df[df["DateTime"].dt.second == 30]

             DateTime  Sales
2 2025-01-01 14:20:30   5000

In [ ]:
# pratice1